### ISSUE TITLE
Runhouse 2023 Roadmap 🚗

### ISSUE THREAD

**Issue by dongreenberg** [run-house/runhouse#13]
Please help prioritize our roadmap! We have a long list of projects we'd like to complete to make Runhouse robust 🦾, comprehensive 🎨, and flexible 🙆‍♀️ across research and production usage. Please comment which items resonate for your use cases, or let us know if there are features we've missed!

## Compute

- [x] On-prem Clusters
- [ ] Sending functions to K8s
- [ ] Sending functions to Slurm
- [ ] HTTP endpoints
  - [ ] Instant HTTP endpoints for Functions (via Ray Serve)
  - [ ] OpenAPI - Auto-generating docs or clients in other programming languages
  - [ ] Custom ASGI apps
- [ ] Asyncio support
- [ ] Sending functions to serverless compute - Modal, AWS, GCP, Azure
- [ ] Auto-handling dependency matrices for packages (e.g. PyTorch<>CUDA versions)
- [ ] Docker
  - [x] Custom images
  - [ ] Sending functions inside a docker container
  - [ ] Runhouse AMIs
- [ ] Autoscaling and multi-region

## Data

- [x] Blobs - AWS, GCP, Azure
- [ ] New Tables - BigQuery, Databricks, Postgres, Snowflake, Redshift, Delta lake
- [ ] KVStores - Redis, BigTable, ElastiCache
- [ ] VectorStores

## Accessibility

- [ ] Monitoring - Prometheus, Grafana, Datadog, Pagerduty
- [ ] Artifact lineage and forking
- [ ] Resource search and discovery (e.g. Backstage)
- [ ] Custom triggers, alerts (including human-in-the-loop), retries

## Management

- [ ] Secrets - Custom Vault, AWS, GCP, Azure, (Akeyless)
- [ ] Groups - SAML, Okta, Azure AD, AWS, GCP
- [ ] Management of underlying resources in dashboard UI
- [x] Resource versioning and history
- [ ] Networking - VPCs, IP allowlists, Sidecars/Service meshes (Envoy/LinkerD/Istio)

## Tutorials
- [ ] Using Runhouse with other ML platforms - e.g. Airflow, Sagemaker, Vertex, KfP, MetaFlow, MLFlow, etc.
- [ ] Continual learning (e.g. DLRM daily retraining)
- [ ] Large-scale Training and HPO
- [ ] Distributed inference (e.g. OPT or BLOOM)
- [ ] E2E model deployment, including ingress and firewall management.

<sub>[KIT-61](https://linear.app/runhouse/issue/KIT-61/runhouse-2023-roadmap-🚗)</sub>

**Comment by sandkoan** [comment]
HTTP Endpoints and Async would be extraordinarily helpful

**Comment by dongreenberg** [comment]
Have you tried running a function with `my_fn.remote()`? Or do you need literal Python async support?

**Comment by sandkoan** [comment]
Now that you mention it, I suppose `.remote()` takes care of what I need. But the endpoints and scaling would be very useful.
