### ISSUE TITLE
Secrets Management Overview + Tracker

### ISSUE THREAD

**Issue by carolineechen** [run-house/runhouse#147]
Overview and progress tracker for secrets management revamp, including new APIs and support for new types of secret types and providers.

## Motivation

Keeping track of secrets and keys for your various cloud, cluster, and dev accounts, and sharing them across dev environments and teammates is manual and messy. Providing secrets management for Runhouse-adjacent work (e.g. cloud providers for Runhouse clusters, API keys used alongside Runhouse functions, etc) makes it easier to onboard Runhouse Den. Even as a standalone, Runhouse Secrets can be an easy way to get started with storing, keeping track of, and sharing keys.

Runhouse already has basic secrets management support, including saving/syncing provider secrets to default locations, and a login/logout flow. The secrets flow is currently quite separate from the rest of RH resource abstractions, but can benefit from inheriting the properties expected from RH resources, including naming, saving, and sharing.

## Design

Converting secrets to a RH resource makes it easier to further develop secrets to support sharing across users/devices, add flexibility to the types of secrets, and extend to new provider-specific secrets.

### Types of Secrets

* Base Secret -- holds a values dict and a paths dict
* Env Vars Secret -- holds env vars keys and value mapping
* Provider Secret -- all-encompassing secret with default (but customizable) path/env vars assumed from the provider. automatically extract or specify values.
* Cluster Secret -- holds values necessary for sshing into or constructing a RH cluster (e.g. key pair values, cluster config settings, password)

### Additional Secrets functions and built-in use cases

* Top level functions for bulk loading/saving/sending/sharing secrets
* Env Var Secret support in RH Env resource
* Cluster Secret support in RH Cluster resource

### Den updates

* Secrets treated as a resource

### BC-Breaking

* Removal of some top level functions, such as `rh.Secrets.put/get`

### Sample Usage

```
custom_secret = rh.secret(name="my_secret", values={"my_key": "my_value"}
custom_secret = custom_secret.write(path="~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~/.rh/secrets/custom_secret.json")

aws_secret = rh.provider_secret("aws")  # extracts from default path or env vars
aws_secret.values
>>> {'access_key': 'XXX_KEY', 'secret_key': 'YYY_KEY'}

lambdalabs_secret = rh.provider_secret("lambda", values={"api_key": "*****"}).write()
cluster.sync_secrets(["aws", "lambda"])

env_secret = rh.env_secret(name="my_env_vars", env_vars=["OPENAI_API_KEY"])  # extracts from os.environ
```

## Progress Tracker

- [X] undefined#135 (Base PR; at parity with current Secrets)
- [ ] Add env var secrets + support in rh.env
- [ ] Add cluster secrets + support in cluster class / sharing
- [ ] Add paths dict to Base (all) secrets
- [X] Additional provider secrets (Planned: OpenAI, Anthropic, WandB, Databricks. Feel free to comment below any others you'd like to see!)
- [X] Improved (more controlled/intuitive) login and logout flow
- [X] undefined\[Den\] Secrets Sharing
- [X] undefined\[Den\] Update Secrets presentation in Den
- [X] undefined\[Marketing\] Improved/more comprehensive tutorial
- [x] undefined\[Marketing\] Blog Post (target Mid Dec)

cc @dongreenberg @jlewitt1angell

<sub>From [SyncLinear.com](https://synclinear.com) | [KIT-88](https://linear.app/runhouse/issue/KIT-88/secrets-management-overview-tracker)</sub>
